absoluteurl: http://pearsonca.github.io
baseurl: /scala-commsim
markdown: kramdown
highlighter: pygments
exclude:
  - 'rscripts'
  - 'src'
  - 'target'
  - 'project'
  - 'simdata'
  - '*.sh'
  - '*.sbt'
