absoluteurl: http://pearsonca.github.io
baseurl: /scala-commsim
markdown: kramdown
highlighter: pygments
exclude:
  - 'rscripts'
  - 'src'
  - 'target'
  - 'project'
  - 'simdata'
  - '*.sh'
  - '*.sbt'
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "page"
    values:
      layout: "mathjax"
