#!/bin/bash
#PBS -r n
#PBS -N minerva
#PBS -o minnow.o
#PBS -e minnow.err
#PBS -m a
#PBS -M cap10@ufl.edu
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=8
#PBS -l pmem=1G
#PBS -t 1-1080

cd /scratch/lfs/cap10
parameters=`cat parameters.txt | tail -n +$PBS_ARRAYID | head -1`
for ((i=0;i<1000;i++))
do
  scala edu.cap10.cora.demo.Pub $parameters > run-$PBS_ARRAYID-$i.csv
  awk '{ print "$PBS_ARRAYID, $i, " $0 }' run-$PBS_ARRAYID-$i.csv >> runs.csv
  rm run-$PBS_ARRAYID-$i.csv
done